server/chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('api/', include('chatapp.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

server/chatapp/urls.py
from django.urls import path
from chatapp.views.user_views import LoginView, logOutView, RegisterView, ForgotPasswordView, checkLoginView
from chatapp.views.chat_views import contactsView, FetchMessages

app_name = "chatapp"
urlpatterns = [
    path('contacts/', contactsView, name='home'),
    path('check-login/', checkLoginView, name='check-login'),
    path('signin/', LoginView.as_view(), name='login'),
    path('signup/', RegisterView.as_view(), name='signup'),
    path('signout/', logOutView, name='sign-out'),
    path('forgot-pass/', ForgotPasswordView.as_view(), name='sign-out'),

    path('messages/<str:room_id>', FetchMessages.as_view())
]

server/chatapp/models/chat_models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
User = get_user_model()


class Conversation(models.Model):
    room_name = models.CharField(max_length=200, unique=True)
    # users = models.ForeignKey(User, on)
    users = models.ManyToManyField(User)

    def __str__(self):
        room_users = ''
        for user in self.users.all():
            room_users += '-' + str(user)
        return f"{room_users[1:]}"

    class Meta:
        verbose_name = 'Conversation'
        verbose_name_plural = 'Conversations'


class Messages(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.conversation}: {self.content}'

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

server/chatapp/models/user_models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models


# Create your models here.


class ChatUsersManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        try:
            user = ChatUsers.objects.get(username=username, **extra_fields)
        except ChatUsers.DoesNotExist:
            user = self.model(username=username, **extra_fields)
            user.set_password(password)
            user.save()
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        if password is None:
            raise TypeError('Password should not be none')
        user = self.create_user(username, password, **extra_fields)
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user

    def get_query(self, excluded_user_id):
        return super().get_queryset().exclude(
            id=excluded_user_id,
        ).exclude(
            is_staff=True,
            is_superuser=True
        )


class ChatUsers(AbstractBaseUser):
    username = models.CharField(max_length=150, unique=True)
    name = models.CharField(max_length=150, default=username)
    password = models.CharField(max_length=128)
    email = models.EmailField(max_length=150)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = ChatUsersManager()

    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    class Meta:
        verbose_name = 'ChatUser'
        verbose_name_plural = 'ChatUsers'

server/chatapp/views/chat_views.py
import os

from django.contrib.auth import get_user_model
from django.http import JsonResponse
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView

from chatapp.models import Messages, Conversation
from chatapp.utils import get_chat_room, customised_sort, get_user_from_request, strip_time_stamp

User = get_user_model()


# Create your views here

@api_view(['GET'])
def contactsView(request):

    # Registering an admin user
    if os.getenv('ON_PRODUCTION') == 'True':
        try:
            admin_user = User.objects.get(username='yll-admin')
        except User.DoesNotExist:
            admin_user = User.objects.create_superuser(
                username='yll-admin',
                password='azerty@#123',
                email='admin@email.com'
            )
        print(admin_user.username)

    # Get the user ID
    request, _ = get_user_from_request(request)

    # Get the contacts for the user
    contacts = User.objects.get_query(request.user.id)
    users_with_timestamps = []
    for user in contacts:
        user_messages = Messages.objects.filter(conversation=get_chat_room(request.user, user))
        l_m = user_messages.order_by('-timestamp').first()
        timestamp = l_m.timestamp if l_m else None
        users_with_timestamps.append((user, timestamp))
    # Sort users based on the latest message timestamp
    contacts = customised_sort(users_with_timestamps)

    contact_list = list()
    for contact in contacts:
        last_message = Messages.objects.filter(conversation=get_chat_room(request.user, contact[0])).last()
        contact_list.append({
            "username": contact[0].username,
            "contact_name": contact[0].name,
            "room_id": get_chat_room(request.user, contact[0]).room_name,
        })
        if last_message:
            contact_list[-1]["last_message"] = last_message.content
            contact_list[-1]["last_message_sender"] = last_message.user.username
            contact_list[-1]["timestamp"] = strip_time_stamp(contact[1])
        else:
            contact_list[-1]["last_message"] = 'empty chat'
            contact_list[-1]["timestamp"] = ''

    return Response(contact_list, status=status.HTTP_200_OK)


class FetchMessages(APIView):
    def get(self, request, room_id: str):
        request, _ = get_user_from_request(request)
        # Get the conversation with the given room ID
        convo = Conversation.objects.get(room_name=room_id)

        # Get all the messages in the conversation
        messages = Messages.objects.filter(conversation=convo)

        # Check if there are no messages
        if messages is None:
            return JsonResponse({'error': 'No messages found'}, status=status.HTTP_404_NOT_FOUND)

        # Create a dictionary to store the messages
        msgs = {"data": []}

        # Iterate over each message
        for msg in messages:
            # Add the message details to the dictionary
            msgs["data"].append({
                "sender": msg.user.username,
                "content": msg.content,
                "timestamp": msg.timestamp
            })

        # Return the messages as a JSON response
        return Response(msgs)

server/chatapp/views/user_views.py
import datetime
import jwt
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.exceptions import AuthenticationFailed, ValidationError
from rest_framework.response import Response
from rest_framework.views import APIView

from chatapp.serializers import UserSerializer

User = get_user_model()


# Create your views here.

class RegisterView(APIView):
    # authentication_classes = [SessionAuthentication]

    # def get(self, request):
    #     return render(request, 'chatapp/signup.html')

    def post(self, request):
        serializer = UserSerializer(data=request.data)
        try:
            serializer.is_valid(raise_exception=True)
            serializer.save()
            return Response(serializer.validated_data, status=status.HTTP_201_CREATED)
        except ValidationError:
            return Response(
                {'message': f" Username {request.data['username']} already exists."},
                status=status.HTTP_400_BAD_REQUEST
            )


class LoginView(APIView):

    def post(self, request):
        # email = request.data["email"]
        username = request.data["username"]
        password = request.data["password"]
        user = User.objects.filter(username=username).first()
        token_expiry_time_in_seconds = 48 * 60 * 60  # Expiring 2 days later
        try:
            if user is None:
                raise AuthenticationFailed('User not Found!')
            elif not user.check_password(password):
                raise AuthenticationFailed('Incorrect password!')
            else:
                payload = {
                    'id': user.id,
                    'exp': datetime.datetime.utcnow() + datetime.timedelta(seconds=token_expiry_time_in_seconds),
                    # 'exp': datetime.datetime.utcnow() + datetime.timedelta(minutes=60*24),  # Expiring 1 day later
                    'iat': datetime.datetime.utcnow()
                }

                token = jwt.encode(payload, 'secret', algorithm='HS256')
                successful_response = Response()
                # We don't want the frontend to access the cookie, so, httponly=True
                successful_response.set_cookie(key='jwt', value=token, httponly=True, samesite='None', secure=True,
                                               max_age=token_expiry_time_in_seconds)
                successful_response.data = {
                    "token": token,
                    'message': "Signup successful",
                    "user": {'username': username, 'name': user.name}
                }
                successful_response.status_code = status.HTTP_201_CREATED
                return successful_response
        except Exception as e:
            print(e)
            return Response({'message': f'{e}'}, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
def checkLoginView(request):
    # Get the JWT token from the request cookie
    try:
        token = request.COOKIES.get('jwt')
        jwt.decode(token, 'secret', algorithms=['HS256'])
        stat = status.HTTP_200_OK if token else status.HTTP_401_UNAUTHORIZED
        return Response({'isLoggedIn': bool(token)}, status=stat)
    except jwt.ExpiredSignatureError:
        # Handle expired token
        return Response({'message': 'Token expired', 'isLoggedIn': False}, status=status.HTTP_401_UNAUTHORIZED)
    except jwt.InvalidTokenError:
        # Handle invalid token
        return Response({'message': 'Invalid token', 'isLoggedIn': False}, status=status.HTTP_401_UNAUTHORIZED)


@api_view(['GET'])
def logOutView(request):
    # logout(request)
    response = Response({})
    response.delete_cookie(key='jwt', samesite='None')
    response.status_code = status.HTTP_200_OK
    return response


class ForgotPasswordView(APIView):
    pass

server/chatapp/templates/chatapp/forgot_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Home</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="{% static 'login.css' %}">
  </head>
  <body>
    <div class="container">
      <div class="center">
          <h1>Forgot Password</h1>
          <form action="{% url 'chatapp:forgot_p' %}" method="POST">
              {% csrf_token %}
              <div class="txt_field">
                  <input type="text" name="username" required>
                  <span></span>
                  <label>Username</label>
              </div>
              <div class="txt_field">
                  <input type="password" name="password" required>
                  <span></span>
                  <label>Password</label>
              </div>
              <div class="pass">Forget Password?</div>
              {% if error %} <p style="color: red; margin-left: 5px">{{ error }}</p> {% endif %}
              <input name="submit" type="Submit" value="Login">
               <div class="signup_link">
                  Not a Member ? <a href="{% url 'chatapp:signup' %}">SignUp</a>
              </div>
          </form>
      </div>
    </div>
  </body>
</html>

server/chatapp/templates/chatapp/index.html
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<!--<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
<!------ Include the above in your HEAD tag ---------->

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<!--<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>-->
<script src="{% static 'jquery-3.7.1.min.js' %}"></script>
<!------ Include the above in your HEAD tag ---------->


<!DOCTYPE html>
<html class='' lang="en">
    <head>
        <script src='//production-assets.codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js'></script><meta charset='UTF-8'><meta name="robots" content="noindex"><link rel="shortcut icon" type="image/x-icon" href="//production-assets.codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico" /><link rel="mask-icon" type="" href="//production-assets.codepen.io/assets/favicon/logo-pin-f2d2b6d2c61838f7e76325261b7195c27224080bc099486ddd6dccb469b8e8e6.svg" color="#111" /><link rel="canonical" href="https://codepen.io/emilcarlsson/pen/ZOQZaV?limit=all&page=74&q=contact+" />
        <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,300' rel='stylesheet' type='text/css'>
        {% block title %}
        <title>chat app</title>
        {% endblock title %}
        <script src="https://use.typekit.net/hoy3lrg.js"></script>
        <script>try{Typekit.load({ async: true });}catch(e){}</script>
        <link rel="stylesheet" href="{% static 'main.css' %}">
<!--        <link rel="stylesheet" href="../../static/main.css">-->
        <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css'><link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.2/css/font-awesome.min.css'>
    </head>
    <body>
        <!-- 

        A concept for a chat interface. 

        Try writing a new message! :)


        Follow me here:
        Twitter: https://twitter.com/thatguyemil
        Codepen: https://codepen.io/emilcarlsson/
        Website: http://emilcarlsson.se/

        -->

        <div id="frame">
            <div id="sidepanel">
                <div id="profile">
                    <div class="wrap">
                        <img id="profile-img" src="http://emilcarlsson.se/assets/mikeross.png" class="online" alt="" />
                        <p>{{ request.user.name }}</p>
<!--                        <i class="fa fa-chevron-down expand-button" aria-hidden="true"></i>-->
<!--                        <div id="status-options">-->
<!--                            <ul>-->
<!--                                <li id="status-online" class="active"><span class="status-circle"></span> <p>Online</p></li>-->
<!--                                <li id="status-away"><span class="status-circle"></span> <p>Away</p></li>-->
<!--                                <li id="status-busy"><span class="status-circle"></span> <p>Busy</p></li>-->
<!--                                <li id="status-offline"><span class="status-circle"></span> <p>Offline</p></li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!--                        <div id="expanded">-->
<!--                            <label for="twitter"><i class="fa fa-facebook fa-fw" aria-hidden="true"></i></label>-->
<!--&lt;!&ndash;                            <input name="twitter" type="text" value="mikeross" />&ndash;&gt;-->
<!--                            <span>mike ross</span>-->
<!--                            <label for="twitter"><i class="fa fa-twitter fa-fw" aria-hidden="true"></i></label>-->
<!--                            <input name="twitter" type="text" value="ross81" />-->
<!--                            <label for="twitter"><i class="fa fa-instagram fa-fw" aria-hidden="true"></i></label>-->
<!--                            <input name="twitter" type="text" value="mike.ross" />-->
<!--                        </div>-->
                    </div>
                </div>
                <div id="search">
                    <label for=""><i class="fa fa-search" aria-hidden="true"></i></label>
                    <input type="text" placeholder="Search contacts..." />
                </div>
                <div id="contacts">
                    <ul>
                    {% for contact in contacts %}
                        <li class="contact"  id="{{ contact.room_id }}">
                            <div class="wrap">
                                <span class="contact-status online"></span>
                                <img src="http://emilcarlsson.se/assets/donnapaulsen.png" alt="" />
                                <div class="meta">
                                    <p class="name">{{ contact.contact_name }}</p>
                                    <p class="preview"><span>{{ contact.last_message }}<span id="timestamp" style="margin-right: 45px;">{{ contact.timestamp }}</span></span></p>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
                <div id="bottom-bar">
                    <a href="{% url 'chatapp:sign-out' %}"><button id="logout"><span>Log Out</span></button></a>
                    <button id="settings"><i class="fa fa-cog fa-fw" aria-hidden="true"></i> <span>Settings</span></button>
                </div>
            </div>
            <div class="content">
            </div>
        </div>
        <script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script>
        <script src='https://code.jquery.com/jquery-2.2.4.min.js'></script>
        <script type="module" src="{% static 'main.js' %}"></script>
        <script>
            const socketty = (roomName) => {
                const chatSocket = new WebSocket("ws://" + window.location.host + `/${roomName.toString()}/`)
                chatSocket.onopen = function (e) {
                    console.log(window.location.host)
                    console.log("The connection was setup successfully !");
                }

                chatSocket.onclose = function (e) {
                    console.log("Error: ", e)
                    console.log("Chat socket closed unexpectedly")
                }

                $('.submit').click(function () {
                    const messageInput = $(".message-input input").val();
                    const roomId = $(".contact.active").attr('id');
                    const username = "{{ request.user.username }}"
                    chatSocket.send(JSON.stringify({
                        "message": messageInput,
                        "room_id": roomId,
                        "sender_username": username
                    }));
                });

                chatSocket.onmessage = function (e) {
                    const data = JSON.parse(e.data);
                    if ($.trim(data.message) === '') {
                        return false;
                    }
                    const isSender = data.sender_username !== "{{ request.user.username }}";
                    const messageClass = isSender ? 'sent' : 'replies';
                    const messageLi = `<li class="${messageClass}"><img src="http://emilcarlsson.se/assets/mikeross.png" alt="" /><p>${data.message}</p></li>`;
                    if ($(".contact.active").attr("id") === data.room_name) {
                        $('.messages ul').append(messageLi)
                    }
                    $('.message-input input').val(null);
                    const previewText = isSender ? '' : 'You: ';
                    $(`#${data.room_name} .preview`).html(`<span>${previewText}${data.message}<span id="timestamp" style="margin-right: 45px;">${data.timestamp}</span></span>`);
                    $(".messages").animate({scrollTop: $(document).height()}, "fast");
                    scrollToBottom()
                }
            };

            $('.contact').click(function () {
                const hasActiveClass = $(this).hasClass('active')
                if (!hasActiveClass) {
                    $('.contact').removeClass('active')
                    $(this).addClass('active')
                    addingDivContent()
                    const name = $('.contact.active p.name').text()
                    $('.contact-profile p').text(name);
                    const roomId = $(this).attr('id')
                    socketty(roomId)
                    fetchMessages(roomId)
                    scrollToBottom()
                }
            });

            const fetchMessages = function (roomId) {
                $.ajax({
                    type: 'GET',
                    url: `/messages/${roomId}`,
                    success: (result) => {
                        $.each(result.data, (index, msg) => {
                            const isSender = msg.sender !== "{{ request.user.username }}";
                            const messageClass = isSender ? 'sent' : 'replies';
                            const messageLi = `<li class="${messageClass}"><img src="http://emilcarlsson.se/assets/mikeross.png" alt="" /><p>${msg.content}</p></li>`;
                            $('.messages ul').append(messageLi)
                        })
                    }
                })
            }

            function scrollToBottom() {
                let messageContainer = $('div.messages')
                messageContainer.scrollTop(messageContainer[0].scrollHeight);
            }


            const addingDivContent = () => {
                $('div.content').html(`<div class="contact-profile">
                            <img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="">
                            <p></p>
                        </div>
                        <div class="messages">
                            <ul>
                            </ul>
                        </div>
                        <div class="message-input">
                            <div class="wrap">
                            <input type="text" placeholder="Write your message...">
                            <i class="fa fa-paperclip attachment" aria-hidden="true"></i>
                            <button class="submit"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                            </div>
                        </div>`)
	        }
        </script>
    </body>
</html>

server/chatapp/templates/chatapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Home</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="{% static 'login.css' %}">
  </head>
  <body>
    <div class="container">
      <div class="center">
          <h1>Login</h1>
          <form action="{% url 'chatapp:login' %}" method="POST">
              {% csrf_token %}
              <div class="txt_field">
                  <input type="text" name="username" required>
                  <span></span>
                  <label>Username</label>
              </div>
              <div class="txt_field">
                  <input type="password" name="password" required>
                  <span></span>
                  <label>Password</label>
              </div>
              <div class="pass">Forget Password?</div>
              {% if error %} <p style="color: red; margin-left: 5px">{{ error }}</p> {% endif %}
              <input name="submit" type="Submit" value="Login">
               <div class="signup_link">
                  Not a Member ? <a href="{% url 'chatapp:signup' %}">SignUp</a>
              </div>
          </form>
      </div>
    </div>
  </body>
</html>

server/chatapp/templates/chatapp/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Home</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="{% static 'login.css' %}">
  </head>
  <body>
    <div class="container">
      <div class="center">
          <h1>Sign up</h1>
          <form action="{% url 'chatapp:signup' %}" method="POST">
              {% csrf_token %}
              <div class="txt_field">
                  <input type="text" name="F_name" required>
                  <span></span>
                  <label>First Name *</label>
              </div>
              <div class="txt_field">
                  <input type="text" name="S_name" required>
                  <span></span>
                  <label>Second Name *</label>
              </div>
              <div class="txt_field">
                  <input type="text" name="username" required>
                  <span></span>
                  <label>Username *</label>
              </div>
              <div class="txt_field">
                  <input type="email" name="email" required>
                  <span></span>
                  <label>Email *</label>
              </div>
              <div class="txt_field">
                  <input type="password" name="password" required>
                  <span></span>
                  <label>Password *</label>
              </div>
              {% if error %} <p style="color: red; margin-left: 5px">{{ error }}</p> {% endif %}
              <input name="submit" type="Submit" value="Sign up">
               <div class="signup_link">
                  Already a Member ? <a href="{% url 'chatapp:login' %}">LOGIN</a>
              </div>
          </form>
      </div>
    </div>
  </body>
</html>